services:
  mysql:
    image: "bitnami/mysql:latest"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=ecom"
      - "MYSQL_ROOT_USER=root"
      - "MYSQL_ROOT_PASSWORD=mypassword"
    ports:
      - "3306:3306"
